[default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
verbosity = 1
remappings = ['ds-test/=lib/ds-test/src/', 'solmate/=lib/solmate/src/']

[ci]
fuzz_runs = 100_000

# See more config options https://github.com/gakonst/foundry/tree/master/config
